gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - grasping_frame_joint
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.1
    grasping_frame_joint:
      goal: 0.05
  gains:
    grasping_frame_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint2_to_joint1
    - joint3_to_joint2
    - joint4_to_joint3
    - joint5_to_joint4
    - joint6_to_joint5
    - joint6output_to_joint6
  constraints:
    goal_time: 5.0
    stopped_velocity_tolerance: 0.1
    joint2_to_joint1:
      goal: 0.05
    joint3_to_joint2:
      goal: 0.05
    joint4_to_joint3:
      goal: 0.05
    joint5_to_joint4:
      goal: 0.05
    joint6_to_joint5:
      goal: 0.05
    joint6output_to_joint6:
      goal: 0.05
  gains:
    joint2_to_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3_to_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4_to_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5_to_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6_to_joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6output_to_joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

      